### ISSUE TITLE
Repair docker builds

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/ml#302] opened 2018-07-25 15:36 UTC
Broken for 16 days https://hub.docker.com/r/srcd/ml/builds/

**Comment by warenlg** [comment] 2018-07-25 20:03
Yes I remember this. However, now, I can't reproduce the error again and it seems somebody edited the ml-core image 5h ago. The last build of the ml image was yesterday. @vmarkovtsev  may I ask you to re-build the ml image please (I can't do it), I suspect it is fixed.

**Comment by vmarkovtsev** [comment] 2018-07-26 08:55
I rebuilt it because I remembered that @zurk asked me to.
OK, then it should go away after the next push.

**Comment by warenlg** [comment] 2018-08-24 10:07
Docker builds OK https://hub.docker.com/r/srcd/ml/builds/
We can close this

**Closed** 2018-08-24 11:13 UTC
